---
- name: Install PHP5-FPM
  sudo: yes
  apt:  package=php5-fpm state=latest

- ini_file: dest=/etc/php5/fpm/php.ini
            option=upload_max_filesize
            value=50M
            backup=yes