---
  - name: Install nginx
    sudo: yes
    apt:  pkg=nginx state=latest

  - name: Ensure nginx log directory exists
    file: dest=/var/log/nginx/symfony state=directory

  - name: Change default nginx site
    sudo: yes
    template: src=picobello.tpl dest=/etc/nginx/sites-available/default
    notify: restart nginx

#include before
 upstream php {
            server unix:/var/run/php5-fpm.sock;
        }

        include /etc/nginx/conf.d/*.conf;
